package lesson4;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.Collections;

//create 2 Collections with SQL-queries and Expected results

public class CollectionTestCases { 			
	
	public boolean checkTestCase (int testCaseNumber){
	for (int i = 1; i <= 3; i++) {
		System.out.println("i = " + i);
		System.out.println(" Key = " + i);
		System.out.println(" Value = " + testCases.get(i));
        System.out.println("ExpectedResults = " + expectedResults.get(i));
        System.out.println("ResultSelectSQLQuery = " + (selectSqlQuery(testCases.get(i)));
        String resultSQLQuery = HomeWork2.selectSqlQuery(testCases.get(i));
	if (resultSQLQuery.equals(Col1.expectedResults.get(i))) {
		System.out.println("Test ¹ " + i + " - PASSED");
	}
		else System.out.println("Test ¹ " + i + " - FAILED");
	}
		}

		public static void main (String args[]) throws SQLException{
			// create Collection with SQL-queries
			Map<Integer,String> testCases = new HashMap<Integer,String>();
			testCases.put(1, "SELECT dutyFree FROM airports WHERE airport = 'London';");
			testCases.put(2, "SELECT dutyFree FROM airports WHERE airport = 'Paris';");
			testCases.put(3, "SELECT dutyFree FROM airports WHERE airport = 'Sydney';");
			testCases.put(4, "SELECT dutyFree FROM airports WHERE airport = 'Berlin';");
			testCases.put(5, "SELECT dutyFree FROM airports WHERE airport = 'Munich';");
			testCases.put(6, "SELECT dutyFree FROM airports WHERE airport = 'New York';");
			testCases.put(7, "SELECT dutyFree FROM airports WHERE airport = 'Kiev';");
			testCases.put(8, "SELECT dutyFree FROM airports WHERE airport = 'Budapest';");
			testCases.put(9, "SELECT dutyFree FROM airports WHERE airport = 'Beijing';");
			testCases.put(10, "SELECT dutyFree FROM airports WHERE airport = 'Prague';");
			testCases.put(11, "SELECT dutyFree FROM airports WHERE airport = 'Helsinki';");
			testCases.put(12, "SELECT dutyFree FROM airports WHERE airport = 'Ottava';");
			testCases.put(13, "SELECT dutyFree FROM airports WHERE airport = 'Vilnius';");
			testCases.put(14, "SELECT dutyFree FROM airports WHERE airport = 'Milan';");
			testCases.put(15, "SELECT dutyFree FROM airports WHERE airport = 'Barcelona';");
			testCases.put(16, "SELECT priorityBoarding FROM airports WHERE airport = 'London';");
			testCases.put(17, "SELECT priorityBoarding FROM airports WHERE airport = 'Paris';");
			testCases.put(18, "SELECT priorityBoarding FROM airports WHERE airport = 'Sydney';");
			testCases.put(19, "SELECT priorityBoarding FROM airports WHERE airport = 'Berlin';");
			testCases.put(20, "SELECT priorityBoarding FROM airports WHERE airport = 'Munich';");
			testCases.put(21, "SELECT priorityBoarding FROM airports WHERE airport = 'New York';");
			testCases.put(22, "SELECT priorityBoarding FROM airports WHERE airport = 'Kiev';");
			testCases.put(23, "SELECT priorityBoarding FROM airports WHERE airport = 'Budapest';");
			testCases.put(24, "SELECT priorityBoarding FROM airports WHERE airport = 'Beijing';");
			testCases.put(25, "SELECT priorityBoarding FROM airports WHERE airport = 'Prague';");
			testCases.put(26, "SELECT priorityBoarding FROM airports WHERE airport = 'Helsinki';");
			testCases.put(27, "SELECT priorityBoarding FROM airports WHERE airport = 'Ottava';");
			testCases.put(28, "SELECT priorityBoarding FROM airports WHERE airport = 'Vilnius';");
			testCases.put(29, "SELECT priorityBoarding FROM airports WHERE airport = 'Milan';");
			testCases.put(30, "SELECT priorityBoarding FROM airports WHERE airport = 'Barcelona';");
			testCases.put(31, "SELECT departureAirport FROM flights WHERE flightNumber = '1001';");
			testCases.put(32, "SELECT departureAirport FROM flights WHERE flightNumber = '1002';");
			testCases.put(33, "SELECT departureAirport FROM flights WHERE flightNumber = '1003';");
			testCases.put(34, "SELECT departureAirport FROM flights WHERE flightNumber = '1004';");
			testCases.put(35, "SELECT departureAirport FROM flights WHERE flightNumber = '1005';");
			testCases.put(36, "SELECT departureAirport FROM flights WHERE flightNumber = '1006';");
			testCases.put(37, "SELECT departureAirport FROM flights WHERE flightNumber = '1007';");
			testCases.put(38, "SELECT departureAirport FROM flights WHERE flightNumber = '1008';");
			testCases.put(39, "SELECT departureAirport FROM flights WHERE flightNumber = '1009';");
			testCases.put(40, "SELECT departureAirport FROM flights WHERE flightNumber = '1010';");
			testCases.put(41, "SELECT departureAirport FROM flights WHERE flightNumber = '1011';");
			testCases.put(42, "SELECT departureAirport FROM flights WHERE flightNumber = '1012';");
			testCases.put(43, "SELECT departureAirport FROM flights WHERE flightNumber = '1013';");
			testCases.put(44, "SELECT departureAirport FROM flights WHERE flightNumber = '1014';");
			testCases.put(45, "SELECT departureAirport FROM flights WHERE flightNumber = '1015';");
			testCases.put(46, "SELECT departureAirport FROM flights WHERE flightNumber = '1016';");
			testCases.put(47, "SELECT departureAirport FROM flights WHERE flightNumber = '1017';");
			testCases.put(48, "SELECT departureAirport FROM flights WHERE flightNumber = '1018';");
			testCases.put(49, "SELECT departureAirport FROM flights WHERE flightNumber = '1019';");
			testCases.put(50, "SELECT departureAirport FROM flights WHERE flightNumber = '1020';");
			testCases.put(51, "SELECT departureAirport FROM flights WHERE flightNumber = '1021';");
			testCases.put(52, "SELECT departureAirport FROM flights WHERE flightNumber = '1022';");
			testCases.put(53, "SELECT departureAirport FROM flights WHERE flightNumber = '1023';");
			testCases.put(54, "SELECT departureAirport FROM flights WHERE flightNumber = '1024';");
			testCases.put(55, "SELECT departureAirport FROM flights WHERE flightNumber = '1025';");
			testCases.put(56, "SELECT departureAirport FROM flights WHERE flightNumber = '1026';");
			testCases.put(57, "SELECT departureAirport FROM flights WHERE flightNumber = '1027';");
			testCases.put(58, "SELECT departureAirport FROM flights WHERE flightNumber = '1028';");
			testCases.put(59, "SELECT departureAirport FROM flights WHERE flightNumber = '1029';");
			testCases.put(60, "SELECT departureAirport FROM flights WHERE flightNumber = '1030';");
			testCases.put(61, "SELECT departureAirport FROM flights WHERE flightNumber = '1031';");
			testCases.put(62, "SELECT departureAirport FROM flights WHERE flightNumber = '1032';");
			testCases.put(63, "SELECT departureAirport FROM flights WHERE flightNumber = '1033';");
			testCases.put(64, "SELECT departureAirport FROM flights WHERE flightNumber = '1034';");
			testCases.put(65, "SELECT departureAirport FROM flights WHERE flightNumber = '1035';");
			testCases.put(66, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1001';");
			testCases.put(67, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1002';");
			testCases.put(68, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1003';");
			testCases.put(69, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1004';");
			testCases.put(70, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1005';");
			testCases.put(71, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1006';");
			testCases.put(72, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1007';");
			testCases.put(73, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1008';");
			testCases.put(74, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1009';");
			testCases.put(75, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1010';");
			testCases.put(76, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1011';");
			testCases.put(77, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1012';");
			testCases.put(78, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1013';");
			testCases.put(79, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1014';");
			testCases.put(80, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1015';");
			testCases.put(81, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1016';");
			testCases.put(82, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1017';");
			testCases.put(83, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1018';");
			testCases.put(84, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1019';");
			testCases.put(85, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1020';");
			testCases.put(86, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1021';");
			testCases.put(87, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1022';");
			testCases.put(88, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1023';");
			testCases.put(89, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1024';");
			testCases.put(90, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1025';");
			testCases.put(91, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1026';");
			testCases.put(92, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1027';");
			testCases.put(93, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1028';");
			testCases.put(94, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1029';");
			testCases.put(95, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1030';");
			testCases.put(96, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1031';");
			testCases.put(97, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1032';");
			testCases.put(98, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1033';");
			testCases.put(99, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1034';");
			testCases.put(100, "SELECT arrivalAirport FROM flights WHERE flightNumber = '1035';");
			testCases.put(101, "SELECT stopsNumber FROM flights WHERE flightNumber = '1001';");
			testCases.put(102, "SELECT stopsNumber FROM flights WHERE flightNumber = '1002';");
			testCases.put(103, "SELECT stopsNumber FROM flights WHERE flightNumber = '1003';");
			testCases.put(104, "SELECT stopsNumber FROM flights WHERE flightNumber = '1004';");
			testCases.put(105, "SELECT stopsNumber FROM flights WHERE flightNumber = '1005';");
			testCases.put(106, "SELECT stopsNumber FROM flights WHERE flightNumber = '1006';");
			testCases.put(107, "SELECT stopsNumber FROM flights WHERE flightNumber = '1007';");
			testCases.put(108, "SELECT stopsNumber FROM flights WHERE flightNumber = '1008';");
			testCases.put(109, "SELECT stopsNumber FROM flights WHERE flightNumber = '1009';");
			testCases.put(110, "SELECT stopsNumber FROM flights WHERE flightNumber = '1010';");
			testCases.put(111, "SELECT stopsNumber FROM flights WHERE flightNumber = '1011';");
			testCases.put(112, "SELECT stopsNumber FROM flights WHERE flightNumber = '1012';");
			testCases.put(113, "SELECT stopsNumber FROM flights WHERE flightNumber = '1013';");
			testCases.put(114, "SELECT stopsNumber FROM flights WHERE flightNumber = '1014';");
			testCases.put(115, "SELECT stopsNumber FROM flights WHERE flightNumber = '1015';");
			testCases.put(116, "SELECT stopsNumber FROM flights WHERE flightNumber = '1016';");
			testCases.put(117, "SELECT stopsNumber FROM flights WHERE flightNumber = '1017';");
			testCases.put(118, "SELECT stopsNumber FROM flights WHERE flightNumber = '1018';");
			testCases.put(119, "SELECT stopsNumber FROM flights WHERE flightNumber = '1019';");
			testCases.put(120, "SELECT stopsNumber FROM flights WHERE flightNumber = '1020';");
			testCases.put(121, "SELECT stopsNumber FROM flights WHERE flightNumber = '1021';");
			testCases.put(122, "SELECT stopsNumber FROM flights WHERE flightNumber = '1022';");
			testCases.put(123, "SELECT stopsNumber FROM flights WHERE flightNumber = '1023';");
			testCases.put(124, "SELECT stopsNumber FROM flights WHERE flightNumber = '1024';");
			testCases.put(125, "SELECT stopsNumber FROM flights WHERE flightNumber = '1025';");
			testCases.put(126, "SELECT stopsNumber FROM flights WHERE flightNumber = '1026';");
			testCases.put(127, "SELECT stopsNumber FROM flights WHERE flightNumber = '1027';");
			testCases.put(128, "SELECT stopsNumber FROM flights WHERE flightNumber = '1028';");
			testCases.put(129, "SELECT stopsNumber FROM flights WHERE flightNumber = '1029';");
			testCases.put(130, "SELECT stopsNumber FROM flights WHERE flightNumber = '1030';");
			testCases.put(131, "SELECT stopsNumber FROM flights WHERE flightNumber = '1031';");
			testCases.put(132, "SELECT stopsNumber FROM flights WHERE flightNumber = '1032';");
			testCases.put(133, "SELECT stopsNumber FROM flights WHERE flightNumber = '1033';");
			testCases.put(134, "SELECT stopsNumber FROM flights WHERE flightNumber = '1034';");
			testCases.put(135, "SELECT stopsNumber FROM flights WHERE flightNumber = '1035';");
			testCases.put(136, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1001';");
			testCases.put(137, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1002';");
			testCases.put(138, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1003';");
			testCases.put(139, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1004';");
			testCases.put(140, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1005';");
			testCases.put(141, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1006';");
			testCases.put(142, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1007';");
			testCases.put(143, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1008';");
			testCases.put(144, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1009';");
			testCases.put(145, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1010';");
			testCases.put(146, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1011';");
			testCases.put(147, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1012';");
			testCases.put(148, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1013';");
			testCases.put(149, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1014';");
			testCases.put(150, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1015';");
			testCases.put(151, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1016';");
			testCases.put(152, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1017';");
			testCases.put(153, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1018';");
			testCases.put(154, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1019';");
			testCases.put(155, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1020';");
			testCases.put(156, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1021';");
			testCases.put(157, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1022';");
			testCases.put(158, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1023';");
			testCases.put(159, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1024';");
			testCases.put(160, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1025';");
			testCases.put(161, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1026';");
			testCases.put(162, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1027';");
			testCases.put(163, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1028';");
			testCases.put(164, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1029';");
			testCases.put(165, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1030';");
			testCases.put(166, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1031';");
			testCases.put(167, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1032';");
			testCases.put(168, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1033';");
			testCases.put(169, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1034';");
			testCases.put(170, "SELECT averageTicketPrice FROM flights WHERE flightNumber = '1035';");
			testCases.put(171, "SELECT availableSeats FROM flights WHERE flightNumber = '1001';");
			testCases.put(172, "SELECT availableSeats FROM flights WHERE flightNumber = '1002';");
			testCases.put(173, "SELECT availableSeats FROM flights WHERE flightNumber = '1003';");
			testCases.put(174, "SELECT availableSeats FROM flights WHERE flightNumber = '1004';");
			testCases.put(175, "SELECT availableSeats FROM flights WHERE flightNumber = '1005';");
			testCases.put(176, "SELECT availableSeats FROM flights WHERE flightNumber = '1006';");
			testCases.put(177, "SELECT availableSeats FROM flights WHERE flightNumber = '1007';");
			testCases.put(178, "SELECT availableSeats FROM flights WHERE flightNumber = '1008';");
			testCases.put(179, "SELECT availableSeats FROM flights WHERE flightNumber = '1009';");
			testCases.put(180, "SELECT availableSeats FROM flights WHERE flightNumber = '1010';");
			testCases.put(181, "SELECT availableSeats FROM flights WHERE flightNumber = '1011';");
			testCases.put(182, "SELECT availableSeats FROM flights WHERE flightNumber = '1012';");
			testCases.put(183, "SELECT availableSeats FROM flights WHERE flightNumber = '1013';");
			testCases.put(184, "SELECT availableSeats FROM flights WHERE flightNumber = '1014';");
			testCases.put(185, "SELECT availableSeats FROM flights WHERE flightNumber = '1015';");
			testCases.put(186, "SELECT availableSeats FROM flights WHERE flightNumber = '1016';");
			testCases.put(187, "SELECT availableSeats FROM flights WHERE flightNumber = '1017';");
			testCases.put(188, "SELECT availableSeats FROM flights WHERE flightNumber = '1018';");
			testCases.put(189, "SELECT availableSeats FROM flights WHERE flightNumber = '1019';");
			testCases.put(190, "SELECT availableSeats FROM flights WHERE flightNumber = '1020';");
			testCases.put(191, "SELECT availableSeats FROM flights WHERE flightNumber = '1021';");
			testCases.put(192, "SELECT availableSeats FROM flights WHERE flightNumber = '1022';");
			testCases.put(193, "SELECT availableSeats FROM flights WHERE flightNumber = '1023';");
			testCases.put(194, "SELECT availableSeats FROM flights WHERE flightNumber = '1024';");
			testCases.put(195, "SELECT availableSeats FROM flights WHERE flightNumber = '1025';");
			testCases.put(196, "SELECT availableSeats FROM flights WHERE flightNumber = '1026';");
			testCases.put(197, "SELECT availableSeats FROM flights WHERE flightNumber = '1027';");
			testCases.put(198, "SELECT availableSeats FROM flights WHERE flightNumber = '1028';");
			testCases.put(199, "SELECT availableSeats FROM flights WHERE flightNumber = '1029';");
			testCases.put(200, "SELECT availableSeats FROM flights WHERE flightNumber = '1030';");
			testCases.put(201, "SELECT availableSeats FROM flights WHERE flightNumber = '1031';");
			testCases.put(202, "SELECT availableSeats FROM flights WHERE flightNumber = '1032';");
			testCases.put(203, "SELECT availableSeats FROM flights WHERE flightNumber = '1033';");
			testCases.put(204, "SELECT availableSeats FROM flights WHERE flightNumber = '1034';");
			testCases.put(205, "SELECT availableSeats FROM flights WHERE flightNumber = '1035';");
			testCases.put(206, "SELECT  FROM  WHERE  = '';");
			testCases.put(207, "SELECT airline FROM airlines WHERE flightNumber = '1001';");
			testCases.put(208, "SELECT airline FROM airlines WHERE flightNumber = '1002';");
			testCases.put(209, "SELECT airline FROM airlines WHERE flightNumber = '1003';");
			testCases.put(210, "SELECT airline FROM airlines WHERE flightNumber = '1004';");
			testCases.put(211, "SELECT airline FROM airlines WHERE flightNumber = '1005';");
			testCases.put(212, "SELECT airline FROM airlines WHERE flightNumber = '1006';");
			testCases.put(213, "SELECT airline FROM airlines WHERE flightNumber = '1007';");
			testCases.put(214, "SELECT airline FROM airlines WHERE flightNumber = '1008';");
			testCases.put(215, "SELECT airline FROM airlines WHERE flightNumber = '1009';");
			testCases.put(216, "SELECT airline FROM airlines WHERE flightNumber = '1010';");
			testCases.put(217, "SELECT airline FROM airlines WHERE flightNumber = '1011';");
			testCases.put(218, "SELECT airline FROM airlines WHERE flightNumber = '1012';");
			testCases.put(219, "SELECT airline FROM airlines WHERE flightNumber = '1013';");
			testCases.put(220, "SELECT airline FROM airlines WHERE flightNumber = '1014';");
			testCases.put(221, "SELECT airline FROM airlines WHERE flightNumber = '1015';");
			testCases.put(222, "SELECT airline FROM airlines WHERE flightNumber = '1016';");
			testCases.put(223, "SELECT airline FROM airlines WHERE flightNumber = '1017';");
			testCases.put(224, "SELECT airline FROM airlines WHERE flightNumber = '1018';");
			testCases.put(225, "SELECT airline FROM airlines WHERE flightNumber = '1019';");
			testCases.put(226, "SELECT airline FROM airlines WHERE flightNumber = '1020';");
			testCases.put(227, "SELECT airline FROM airlines WHERE flightNumber = '1021';");
			testCases.put(228, "SELECT airline FROM airlines WHERE flightNumber = '1022';");
			testCases.put(229, "SELECT airline FROM airlines WHERE flightNumber = '1023';");
			testCases.put(230, "SELECT airline FROM airlines WHERE flightNumber = '1024';");
			testCases.put(231, "SELECT airline FROM airlines WHERE flightNumber = '1025';");
			testCases.put(232, "SELECT airline FROM airlines WHERE flightNumber = '1026';");
			testCases.put(233, "SELECT airline FROM airlines WHERE flightNumber = '1027';");
			testCases.put(234, "SELECT airline FROM airlines WHERE flightNumber = '1028';");
			testCases.put(235, "SELECT airline FROM airlines WHERE flightNumber = '1029';");
			testCases.put(236, "SELECT airline FROM airlines WHERE flightNumber = '1030';");
			testCases.put(237, "SELECT airline FROM airlines WHERE flightNumber = '1031';");
			testCases.put(238, "SELECT airline FROM airlines WHERE flightNumber = '1032';");
			testCases.put(239, "SELECT airline FROM airlines WHERE flightNumber = '1033';");
			testCases.put(240, "SELECT airline FROM airlines WHERE flightNumber = '1034';");
			testCases.put(241, "SELECT airline FROM airlines WHERE flightNumber = '1035';");
			testCases.put(242, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1001';");
			testCases.put(243, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1002';");
			testCases.put(244, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1003';");
			testCases.put(245, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1004';");
			testCases.put(246, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1005';");
			testCases.put(247, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1006';");
			testCases.put(248, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1007';");
			testCases.put(249, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1008';");
			testCases.put(250, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1009';");
			testCases.put(251, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1010';");
			testCases.put(252, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1011';");
			testCases.put(253, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1012';");
			testCases.put(254, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1013';");
			testCases.put(255, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1014';");
			testCases.put(256, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1015';");
			testCases.put(257, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1016';");
			testCases.put(258, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1017';");
			testCases.put(259, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1018';");
			testCases.put(260, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1019';");
			testCases.put(261, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1020';");
			testCases.put(262, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1021';");
			testCases.put(263, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1022';");
			testCases.put(264, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1023';");
			testCases.put(265, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1024';");
			testCases.put(266, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1025';");
			testCases.put(267, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1026';");
			testCases.put(268, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1027';");
			testCases.put(269, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1028';");
			testCases.put(270, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1029';");
			testCases.put(271, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1030';");
			testCases.put(272, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1031';");
			testCases.put(273, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1032';");
			testCases.put(274, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1033';");
			testCases.put(275, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1034';");
			testCases.put(276, "SELECT additionalSpaceService FROM airlines WHERE flightNumber = '1035';");
			testCases.put(277, "SELECT webRegistration FROM airlines WHERE flightNumber = '1001';");
			testCases.put(278, "SELECT webRegistration FROM airlines WHERE flightNumber = '1002';");
			testCases.put(279, "SELECT webRegistration FROM airlines WHERE flightNumber = '1003';");
			testCases.put(280, "SELECT webRegistration FROM airlines WHERE flightNumber = '1004';");
			testCases.put(281, "SELECT webRegistration FROM airlines WHERE flightNumber = '1005';");
			testCases.put(282, "SELECT webRegistration FROM airlines WHERE flightNumber = '1006';");
			testCases.put(283, "SELECT webRegistration FROM airlines WHERE flightNumber = '1007';");
			testCases.put(284, "SELECT webRegistration FROM airlines WHERE flightNumber = '1008';");
			testCases.put(285, "SELECT webRegistration FROM airlines WHERE flightNumber = '1009';");
			testCases.put(286, "SELECT webRegistration FROM airlines WHERE flightNumber = '1010';");
			testCases.put(287, "SELECT webRegistration FROM airlines WHERE flightNumber = '1011';");
			testCases.put(288, "SELECT webRegistration FROM airlines WHERE flightNumber = '1012';");
			testCases.put(289, "SELECT webRegistration FROM airlines WHERE flightNumber = '1013';");
			testCases.put(290, "SELECT webRegistration FROM airlines WHERE flightNumber = '1014';");
			testCases.put(291, "SELECT webRegistration FROM airlines WHERE flightNumber = '1015';");
			testCases.put(292, "SELECT webRegistration FROM airlines WHERE flightNumber = '1016';");
			testCases.put(293, "SELECT webRegistration FROM airlines WHERE flightNumber = '1017';");
			testCases.put(294, "SELECT webRegistration FROM airlines WHERE flightNumber = '1018';");
			testCases.put(295, "SELECT webRegistration FROM airlines WHERE flightNumber = '1019';");
			testCases.put(296, "SELECT webRegistration FROM airlines WHERE flightNumber = '1020';");
			testCases.put(297, "SELECT webRegistration FROM airlines WHERE flightNumber = '1021';");
			testCases.put(298, "SELECT webRegistration FROM airlines WHERE flightNumber = '1022';");
			testCases.put(299, "SELECT webRegistration FROM airlines WHERE flightNumber = '1023';");
			testCases.put(300, "SELECT webRegistration FROM airlines WHERE flightNumber = '1024';");
			testCases.put(301, "SELECT webRegistration FROM airlines WHERE flightNumber = '1025';");
			testCases.put(302, "SELECT webRegistration FROM airlines WHERE flightNumber = '1026';");
			testCases.put(303, "SELECT webRegistration FROM airlines WHERE flightNumber = '1027';");
			testCases.put(304, "SELECT webRegistration FROM airlines WHERE flightNumber = '1028';");
			testCases.put(305, "SELECT webRegistration FROM airlines WHERE flightNumber = '1029';");
			testCases.put(306, "SELECT webRegistration FROM airlines WHERE flightNumber = '1030';");
			testCases.put(307, "SELECT webRegistration FROM airlines WHERE flightNumber = '1031';");
			testCases.put(308, "SELECT webRegistration FROM airlines WHERE flightNumber = '1032';");
			testCases.put(309, "SELECT webRegistration FROM airlines WHERE flightNumber = '1033';");
			testCases.put(310, "SELECT webRegistration FROM airlines WHERE flightNumber = '1034';");
			testCases.put(311, "SELECT webRegistration FROM airlines WHERE flightNumber = '1035';");
			testCases.put(312, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1001';");
			testCases.put(313, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1002';");
			testCases.put(314, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1003';");
			testCases.put(315, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1004';");
			testCases.put(316, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1005';");
			testCases.put(317, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1006';");
			testCases.put(318, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1007';");
			testCases.put(319, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1008';");
			testCases.put(320, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1009';");
			testCases.put(321, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1010';");
			testCases.put(322, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1011';");
			testCases.put(323, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1012';");
			testCases.put(324, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1013';");
			testCases.put(325, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1014';");
			testCases.put(326, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1015';");
			testCases.put(327, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1016';");
			testCases.put(328, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1017';");
			testCases.put(329, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1018';");
			testCases.put(330, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1019';");
			testCases.put(331, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1020';");
			testCases.put(332, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1021';");
			testCases.put(333, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1022';");
			testCases.put(334, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1023';");
			testCases.put(335, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1024';");
			testCases.put(336, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1025';");
			testCases.put(337, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1026';");
			testCases.put(338, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1027';");
			testCases.put(339, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1028';");
			testCases.put(340, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1029';");
			testCases.put(341, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1030';");
			testCases.put(342, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1031';");
			testCases.put(343, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1032';");
			testCases.put(344, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1033';");
			testCases.put(345, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1034';");
			testCases.put(346, "SELECT isMealincluded FROM airlines WHERE flightNumber = '1035';");
			testCases.put(347, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1001';");
			testCases.put(348, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1002';");
			testCases.put(349, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1003';");
			testCases.put(350, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1004';");
			testCases.put(351, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1005';");
			testCases.put(352, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1006';");
			testCases.put(353, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1007';");
			testCases.put(354, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1008';");
			testCases.put(355, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1009';");
			testCases.put(356, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1010';");
			testCases.put(357, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1011';");
			testCases.put(358, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1012';");
			testCases.put(359, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1013';");
			testCases.put(360, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1014';");
			testCases.put(361, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1015';");
			testCases.put(362, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1016';");
			testCases.put(363, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1017';");
			testCases.put(364, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1018';");
			testCases.put(365, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1019';");
			testCases.put(366, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1020';");
			testCases.put(367, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1021';");
			testCases.put(368, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1022';");
			testCases.put(369, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1023';");
			testCases.put(370, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1024';");
			testCases.put(371, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1025';");
			testCases.put(372, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1026';");
			testCases.put(373, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1027';");
			testCases.put(374, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1028';");
			testCases.put(375, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1029';");
			testCases.put(376, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1030';");
			testCases.put(377, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1031';");
			testCases.put(378, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1032';");
			testCases.put(379, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1033';");
			testCases.put(380, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1034';");
			testCases.put(381, "SELECT dutyFree FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1035';");
			testCases.put(382, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1001';");
			testCases.put(383, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1002';");
			testCases.put(384, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1003';");
			testCases.put(385, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1004';");
			testCases.put(386, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1005';");
			testCases.put(387, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1006';");
			testCases.put(388, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1007';");
			testCases.put(389, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1008';");
			testCases.put(390, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1009';");
			testCases.put(391, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1010';");
			testCases.put(392, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1011';");
			testCases.put(393, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1012';");
			testCases.put(394, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1013';");
			testCases.put(395, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1014';");
			testCases.put(396, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1015';");
			testCases.put(397, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1016';");
			testCases.put(398, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1017';");
			testCases.put(399, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1018';");
			testCases.put(400, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1019';");
			testCases.put(401, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1020';");
			testCases.put(402, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1021';");
			testCases.put(403, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1022';");
			testCases.put(404, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1023';");
			testCases.put(405, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1024';");
			testCases.put(406, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1025';");
			testCases.put(407, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1026';");
			testCases.put(408, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1027';");
			testCases.put(409, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1028';");
			testCases.put(410, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1029';");
			testCases.put(411, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1030';");
			testCases.put(412, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1031';");
			testCases.put(413, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1032';");
			testCases.put(414, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1033';");
			testCases.put(415, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1034';");
			testCases.put(416, "SELECT priorityBoarding FROM airports JOIN flights ON departureAirport = airport WHERE flightNumber = '1035';");
			testCases.put(417, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1001';");
			testCases.put(418, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1002';");
			testCases.put(419, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1003';");
			testCases.put(420, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1004';");
			testCases.put(421, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1005';");
			testCases.put(422, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1006';");
			testCases.put(423, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1007';");
			testCases.put(424, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1008';");
			testCases.put(425, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1009';");
			testCases.put(426, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1010';");
			testCases.put(427, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1011';");
			testCases.put(428, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1012';");
			testCases.put(429, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1013';");
			testCases.put(430, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1014';");
			testCases.put(431, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1015';");
			testCases.put(432, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1016';");
			testCases.put(433, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1017';");
			testCases.put(434, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1018';");
			testCases.put(435, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1019';");
			testCases.put(436, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1020';");
			testCases.put(437, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1021';");
			testCases.put(438, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1022';");
			testCases.put(439, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1023';");
			testCases.put(440, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1024';");
			testCases.put(441, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1025';");
			testCases.put(442, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1026';");
			testCases.put(443, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1027';");
			testCases.put(444, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1028';");
			testCases.put(445, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1029';");
			testCases.put(446, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1030';");
			testCases.put(447, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1031';");
			testCases.put(448, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1032';");
			testCases.put(449, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1033';");
			testCases.put(450, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1034';");
			testCases.put(451, "SELECT dutyFree FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1035';");
			testCases.put(452, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1001';");
			testCases.put(453, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1002';");
			testCases.put(454, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1003';");
			testCases.put(455, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1004';");
			testCases.put(456, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1005';");
			testCases.put(457, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1006';");
			testCases.put(458, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1007';");
			testCases.put(459, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1008';");
			testCases.put(460, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1009';");
			testCases.put(461, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1010';");
			testCases.put(462, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1011';");
			testCases.put(463, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1012';");
			testCases.put(464, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1013';");
			testCases.put(465, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1014';");
			testCases.put(466, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1015';");
			testCases.put(467, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1016';");
			testCases.put(468, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1017';");
			testCases.put(469, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1018';");
			testCases.put(470, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1019';");
			testCases.put(471, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1020';");
			testCases.put(472, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1021';");
			testCases.put(473, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1022';");
			testCases.put(474, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1023';");
			testCases.put(475, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1024';");
			testCases.put(476, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1025';");
			testCases.put(477, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1026';");
			testCases.put(478, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1027';");
			testCases.put(479, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1028';");
			testCases.put(480, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1029';");
			testCases.put(481, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1030';");
			testCases.put(482, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1031';");
			testCases.put(483, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1032';");
			testCases.put(484, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1033';");
			testCases.put(485, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1034';");
			testCases.put(486, "SELECT priorityBoarding FROM airports JOIN flights ON arrivalAirport = airport WHERE flightNumber = '1035';");
			testCases.put(487, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'London' AND arrivalAirport = 'Munich');");
			testCases.put(488, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'London' AND arrivalAirport = 'New York');");
			testCases.put(489, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'London' AND arrivalAirport = 'Ottava');");
			testCases.put(490, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'London' AND arrivalAirport = 'Milan');");
			testCases.put(491, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'New York' AND arrivalAirport = 'Sydney');");
			testCases.put(492, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'New York' AND arrivalAirport = 'Kiev');");
			testCases.put(493, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'New York' AND arrivalAirport = 'Milan');");
			testCases.put(494, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'New York' AND arrivalAirport = 'Barcelona');");
			testCases.put(495, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'New York' AND arrivalAirport = 'Prague');");
			testCases.put(496, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'New York' AND arrivalAirport = 'Helsinki');");
			testCases.put(497, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Budapest' AND arrivalAirport = 'London');");
			testCases.put(498, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Budapest' AND arrivalAirport = 'Kiev');");
			testCases.put(499, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Budapest' AND arrivalAirport = 'Vilnius');");
			testCases.put(500, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Beijing' AND arrivalAirport = 'Helsinki');");
			testCases.put(501, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Beijing' AND arrivalAirport = 'Barcelona');");
			testCases.put(502, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Sydney' AND arrivalAirport = 'Berlin');");
			testCases.put(503, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Sydney' AND arrivalAirport = 'Munich');");
			testCases.put(504, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Sydney' AND arrivalAirport = 'Milan');");
			testCases.put(505, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Paris' AND arrivalAirport = 'Ottava');");
			testCases.put(506, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Paris' AND arrivalAirport = 'Vilnius');");
			testCases.put(507, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Paris' AND arrivalAirport = 'Helsinki');");
			testCases.put(508, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Paris' AND arrivalAirport = 'New York');");
			testCases.put(509, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Kiev' AND arrivalAirport = 'New York');");
			testCases.put(510, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Kiev' AND arrivalAirport = 'Milan');");
			testCases.put(511, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Munich' AND arrivalAirport = 'London');");
			testCases.put(512, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Ottava' AND arrivalAirport = 'Vilnius');");
			testCases.put(513, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Ottava' AND arrivalAirport = 'Milan');");
			testCases.put(514, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Ottava' AND arrivalAirport = 'Barcelona');");
			testCases.put(515, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Berlin' AND arrivalAirport = 'Kiev');");
			testCases.put(516, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Prague' AND arrivalAirport = 'Helsinki');");
			testCases.put(517, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Barcelona' AND arrivalAirport = 'Ottava');");
			testCases.put(518, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Helsinki' AND arrivalAirport = 'Budapest');");
			testCases.put(519, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Milan' AND arrivalAirport = 'Beijing');");
			testCases.put(520, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Milan' AND arrivalAirport = 'Sydney');");
			testCases.put(521, "SELECT additionalSpaceService FROM airlines JOIN flights ON airlines.flightNumber = flights.flightNumber WHERE (departureAirport = 'Vilnius' AND arrivalAirport = 'Munich');");
			testCases.put(522, "SELECT dutyFree FROM airports JOIN flights ON airports.airport = flights.departureAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE (airline = 'WizzAir') LIMIT 1;");
			testCases.put(523, "SELECT dutyFree FROM airports JOIN flights ON airports.airport = flights.departureAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE (airline = 'Lufthansa') LIMIT 1;");
			testCases.put(524, "SELECT dutyFree FROM airports JOIN flights ON airports.airport = flights.departureAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE (airline = 'Windrose Aero') LIMIT 1;");
			testCases.put(525, "SELECT dutyFree FROM airports JOIN flights ON airports.airport = flights.departureAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE (airline = 'Cathay Pacific') LIMIT 1;");
			testCases.put(526, "SELECT dutyFree FROM airports JOIN flights ON airports.airport = flights.departureAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE (airline = 'Austrian Airlines') LIMIT 1;");
			testCases.put(527, "SELECT dutyFree FROM airports JOIN flights ON airports.airport = flights.departureAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE (airline = 'AirAsia') LIMIT 1;");
			testCases.put(528, "SELECT dutyFree FROM airports JOIN flights ON airports.airport = flights.departureAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE (airline = 'Virgin') LIMIT 1;");
			testCases.put(529, "SELECT dutyFree FROM airports JOIN flights ON airports.airport = flights.departureAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE (airline = 'Emirates') LIMIT 1;");
			testCases.put(530, "SELECT flights.flightNumber FROM flights JOIN airports ON airports.airport = flights.departureAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE (departureAirport = 'London' AND arrivalAirport = 'Munich' AND averageTicketPrice < 120 AND additionalSpaceService = 'yes' AND priorityBoarding = 'yes');");
			testCases.put(531, "SELECT flights.flightNumber FROM flights JOIN airports ON airports.airport = flights.arrivalAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE (departureAirport = 'New York' AND stopsNumber = 0 AND averageTicketPrice < 500 AND isMealincluded = 'yes' AND dutyFree = 'yes');");
			testCases.put(532, "SELECT flights.flightNumber FROM flights JOIN airports ON airports.airport = flights.arrivalAirport JOIN airlines ON flights.flightNumber = airlines.flightNumber WHERE ((arrivalAirport = 'Milan' OR arrivalAirport = 'Helsinki') AND webRegistration = 'yes' AND averageTicketPrice < 100);");
		
			// create Collection with Expected results
			Map<Integer,String> expectedResults = new HashMap<Integer,String>();
			expectedResults.put(1, "yes");
			expectedResults.put(2, "yes");
			expectedResults.put(3, "no");
			expectedResults.put(4, "yes");
			expectedResults.put(5, "yes");
			expectedResults.put(6, "no");
			expectedResults.put(7, "yes");
			expectedResults.put(8, "yes");
			expectedResults.put(9, "no");
			expectedResults.put(10, "yes");
			expectedResults.put(11, "no");
			expectedResults.put(12, "no");
			expectedResults.put(13, "yes");
			expectedResults.put(14, "yes");
			expectedResults.put(15, "yes");
			expectedResults.put(16, "yes");
			expectedResults.put(17, "yes");
			expectedResults.put(18, "no");
			expectedResults.put(19, "no");
			expectedResults.put(20, "no");
			expectedResults.put(21, "no");
			expectedResults.put(22, "yes");
			expectedResults.put(23, "no");
			expectedResults.put(24, "yes");
			expectedResults.put(25, "yes");
			expectedResults.put(26, "no");
			expectedResults.put(27, "no");
			expectedResults.put(28, "yes");
			expectedResults.put(29, "yes");
			expectedResults.put(30, "no");
			expectedResults.put(31, "London");
			expectedResults.put(32, "London");
			expectedResults.put(33, "London");
			expectedResults.put(34, "London");
			expectedResults.put(35, "New York");
			expectedResults.put(36, "New York");
			expectedResults.put(37, "New York");
			expectedResults.put(38, "New York");
			expectedResults.put(39, "New York");
			expectedResults.put(40, "New York");
			expectedResults.put(41, "Budapest");
			expectedResults.put(42, "Budapest");
			expectedResults.put(43, "Budapest");
			expectedResults.put(44, "Beijing");
			expectedResults.put(45, "Beijing");
			expectedResults.put(46, "Sydney");
			expectedResults.put(47, "Sydney");
			expectedResults.put(48, "Sydney");
			expectedResults.put(49, "Paris");
			expectedResults.put(50, "Paris");
			expectedResults.put(51, "Paris");
			expectedResults.put(52, "Paris");
			expectedResults.put(53, "Kiev");
			expectedResults.put(54, "Kiev");
			expectedResults.put(55, "Munich");
			expectedResults.put(56, "Ottava");
			expectedResults.put(57, "Ottava");
			expectedResults.put(58, "Ottava");
			expectedResults.put(59, "Berlin");
			expectedResults.put(60, "Prague");
			expectedResults.put(61, "Barcelona");
			expectedResults.put(62, "Helsinki");
			expectedResults.put(63, "Milan");
			expectedResults.put(64, "Milan");
			expectedResults.put(65, "Vilnius");
			expectedResults.put(66, "Munich");
			expectedResults.put(67, "New York");
			expectedResults.put(68, "Ottava");
			expectedResults.put(69, "Milan");
			expectedResults.put(70, "Sydney");
			expectedResults.put(71, "Kiev");
			expectedResults.put(72, "Milan");
			expectedResults.put(73, "Barcelona");
			expectedResults.put(74, "Prague");
			expectedResults.put(75, "Helsinki");
			expectedResults.put(76, "London");
			expectedResults.put(77, "Kiev");
			expectedResults.put(78, "Vilnius");
			expectedResults.put(79, "Helsinki");
			expectedResults.put(80, "Barcelona");
			expectedResults.put(81, "Berlin");
			expectedResults.put(82, "Munich");
			expectedResults.put(83, "Milan");
			expectedResults.put(84, "Ottava");
			expectedResults.put(85, "Vilnius");
			expectedResults.put(86, "Helsinki");
			expectedResults.put(87, "New York");
			expectedResults.put(88, "New York");
			expectedResults.put(89, "Milan");
			expectedResults.put(90, "London");
			expectedResults.put(91, "Vilnius");
			expectedResults.put(92, "Milan");
			expectedResults.put(93, "Barcelona");
			expectedResults.put(94, "Kiev");
			expectedResults.put(95, "Helsinki");
			expectedResults.put(96, "Ottava");
			expectedResults.put(97, "Budapest");
			expectedResults.put(98, "Beijing");
			expectedResults.put(99, "Sydney");
			expectedResults.put(100, "Munich");
			expectedResults.put(101, "0");
			expectedResults.put(102, "1");
			expectedResults.put(103, "1");
			expectedResults.put(104, "0");
			expectedResults.put(105, "2");
			expectedResults.put(106, "1");
			expectedResults.put(107, "1");
			expectedResults.put(108, "0");
			expectedResults.put(109, "1");
			expectedResults.put(110, "1");
			expectedResults.put(111, "0");
			expectedResults.put(112, "0");
			expectedResults.put(113, "0");
			expectedResults.put(114, "2");
			expectedResults.put(115, "1");
			expectedResults.put(116, "1");
			expectedResults.put(117, "1");
			expectedResults.put(118, "1");
			expectedResults.put(119, "1");
			expectedResults.put(120, "0");
			expectedResults.put(121, "0");
			expectedResults.put(122, "0");
			expectedResults.put(123, "2");
			expectedResults.put(124, "0");
			expectedResults.put(125, "0");
			expectedResults.put(126, "1");
			expectedResults.put(127, "1");
			expectedResults.put(128, "1");
			expectedResults.put(129, "0");
			expectedResults.put(130, "1");
			expectedResults.put(131, "1");
			expectedResults.put(132, "0");
			expectedResults.put(133, "2");
			expectedResults.put(134, "2");
			expectedResults.put(135, "0");
			expectedResults.put(136, "90");
			expectedResults.put(137, "300");
			expectedResults.put(138, "290");
			expectedResults.put(139, "45");
			expectedResults.put(140, "681");
			expectedResults.put(141, "220");
			expectedResults.put(142, "440");
			expectedResults.put(143, "375");
			expectedResults.put(144, "410");
			expectedResults.put(145, "200");
			expectedResults.put(146, "15");
			expectedResults.put(147, "39");
			expectedResults.put(148, "50");
			expectedResults.put(149, "190");
			expectedResults.put(150, "149");
			expectedResults.put(151, "800");
			expectedResults.put(152, "1200");
			expectedResults.put(153, "1000");
			expectedResults.put(154, "999");
			expectedResults.put(155, "67");
			expectedResults.put(156, "95");
			expectedResults.put(157, "212");
			expectedResults.put(158, "220");
			expectedResults.put(159, "99");
			expectedResults.put(160, "15");
			expectedResults.put(161, "333");
			expectedResults.put(162, "310");
			expectedResults.put(163, "310");
			expectedResults.put(164, "87");
			expectedResults.put(165, "87");
			expectedResults.put(166, "310");
			expectedResults.put(167, "94");
			expectedResults.put(168, "190");
			expectedResults.put(169, "725");
			expectedResults.put(170, "41");
			expectedResults.put(171, "12");
			expectedResults.put(172, "0");
			expectedResults.put(173, "2");
			expectedResults.put(174, "33");
			expectedResults.put(175, "17");
			expectedResults.put(176, "80");
			expectedResults.put(177, "1");
			expectedResults.put(178, "14");
			expectedResults.put(179, "21");
			expectedResults.put(180, "5");
			expectedResults.put(181, "47");
			expectedResults.put(182, "0");
			expectedResults.put(183, "11");
			expectedResults.put(184, "33");
			expectedResults.put(185, "13");
			expectedResults.put(186, "13");
			expectedResults.put(187, "13");
			expectedResults.put(188, "9");
			expectedResults.put(189, "2");
			expectedResults.put(190, "3");
			expectedResults.put(191, "10");
			expectedResults.put(192, "10");
			expectedResults.put(193, "25");
			expectedResults.put(194, "8");
			expectedResults.put(195, "0");
			expectedResults.put(196, "0");
			expectedResults.put(197, "1");
			expectedResults.put(198, "4");
			expectedResults.put(199, "7");
			expectedResults.put(200, "23");
			expectedResults.put(201, "6");
			expectedResults.put(202, "8");
			expectedResults.put(203, "0");
			expectedResults.put(204, "2");
			expectedResults.put(205, "100");
			expectedResults.put(206, "");
			expectedResults.put(207, "WizzAir");
			expectedResults.put(208, "WizzAir");
			expectedResults.put(209, "Lufthansa");
			expectedResults.put(210, "Lufthansa");
			expectedResults.put(211, "Lufthansa");
			expectedResults.put(212, "Lufthansa");
			expectedResults.put(213, "Windrose Aero");
			expectedResults.put(214, "Windrose Aero");
			expectedResults.put(215, "WizzAir");
			expectedResults.put(216, "Cathay Pacific");
			expectedResults.put(217, "Cathay Pacific");
			expectedResults.put(218, "Austrian Airlines");
			expectedResults.put(219, "AirAsia");
			expectedResults.put(220, "Virgin");
			expectedResults.put(221, "Virgin");
			expectedResults.put(222, "Virgin");
			expectedResults.put(223, "AirAsia");
			expectedResults.put(224, "Emirates");
			expectedResults.put(225, "Ryanair");
			expectedResults.put(226, "AirAsia");
			expectedResults.put(227, "Windrose Aero");
			expectedResults.put(228, "WizzAir");
			expectedResults.put(229, "AirAsia");
			expectedResults.put(230, "AirAsia");
			expectedResults.put(231, "Emirates");
			expectedResults.put(232, "WizzAir");
			expectedResults.put(233, "Emirates");
			expectedResults.put(234, "Austrian Airlines");
			expectedResults.put(235, "Turkish Airlines");
			expectedResults.put(236, "Air France");
			expectedResults.put(237, "Air France");
			expectedResults.put(238, "Air France");
			expectedResults.put(239, "Air France");
			expectedResults.put(240, "WizzAir");
			expectedResults.put(241, "Ryanair");
			expectedResults.put(242, "yes");
			expectedResults.put(243, "no");
			expectedResults.put(244, "no");
			expectedResults.put(245, "yes");
			expectedResults.put(246, "no");
			expectedResults.put(247, "yes");
			expectedResults.put(248, "yes");
			expectedResults.put(249, "yes");
			expectedResults.put(250, "no");
			expectedResults.put(251, "no");
			expectedResults.put(252, "yes");
			expectedResults.put(253, "no");
			expectedResults.put(254, "no");
			expectedResults.put(255, "no");
			expectedResults.put(256, "yes");
			expectedResults.put(257, "yes");
			expectedResults.put(258, "no");
			expectedResults.put(259, "yes");
			expectedResults.put(260, "no");
			expectedResults.put(261, "yes");
			expectedResults.put(262, "no");
			expectedResults.put(263, "no");
			expectedResults.put(264, "yes");
			expectedResults.put(265, "no");
			expectedResults.put(266, "yes");
			expectedResults.put(267, "yes");
			expectedResults.put(268, "no");
			expectedResults.put(269, "no");
			expectedResults.put(270, "yes");
			expectedResults.put(271, "yes");
			expectedResults.put(272, "yes");
			expectedResults.put(273, "yes");
			expectedResults.put(274, "no");
			expectedResults.put(275, "no");
			expectedResults.put(276, "no");
			expectedResults.put(277, "no");
			expectedResults.put(278, "no");
			expectedResults.put(279, "yes");
			expectedResults.put(280, "yes");
			expectedResults.put(281, "no");
			expectedResults.put(282, "no");
			expectedResults.put(283, "no");
			expectedResults.put(284, "no");
			expectedResults.put(285, "no");
			expectedResults.put(286, "yes");
			expectedResults.put(287, "yes");
			expectedResults.put(288, "yes");
			expectedResults.put(289, "yes");
			expectedResults.put(290, "yes");
			expectedResults.put(291, "no");
			expectedResults.put(292, "yes");
			expectedResults.put(293, "no");
			expectedResults.put(294, "yes");
			expectedResults.put(295, "no");
			expectedResults.put(296, "no");
			expectedResults.put(297, "no");
			expectedResults.put(298, "no");
			expectedResults.put(299, "yes");
			expectedResults.put(300, "no");
			expectedResults.put(301, "yes");
			expectedResults.put(302, "no");
			expectedResults.put(303, "yes");
			expectedResults.put(304, "no");
			expectedResults.put(305, "yes");
			expectedResults.put(306, "no");
			expectedResults.put(307, "no");
			expectedResults.put(308, "yes");
			expectedResults.put(309, "yes");
			expectedResults.put(310, "yes");
			expectedResults.put(311, "yes");
			expectedResults.put(312, "no");
			expectedResults.put(313, "no");
			expectedResults.put(314, "no");
			expectedResults.put(315, "yes");
			expectedResults.put(316, "yes");
			expectedResults.put(317, "yes");
			expectedResults.put(318, "yes");
			expectedResults.put(319, "yes");
			expectedResults.put(320, "no");
			expectedResults.put(321, "yes");
			expectedResults.put(322, "no");
			expectedResults.put(323, "yes");
			expectedResults.put(324, "yes");
			expectedResults.put(325, "yes");
			expectedResults.put(326, "no");
			expectedResults.put(327, "no");
			expectedResults.put(328, "no");
			expectedResults.put(329, "yes");
			expectedResults.put(330, "no");
			expectedResults.put(331, "yes");
			expectedResults.put(332, "no");
			expectedResults.put(333, "no");
			expectedResults.put(334, "yes");
			expectedResults.put(335, "no");
			expectedResults.put(336, "yes");
			expectedResults.put(337, "yes");
			expectedResults.put(338, "no");
			expectedResults.put(339, "no");
			expectedResults.put(340, "yes");
			expectedResults.put(341, "no");
			expectedResults.put(342, "yes");
			expectedResults.put(343, "no");
			expectedResults.put(344, "no");
			expectedResults.put(345, "yes");
			expectedResults.put(346, "no");
			expectedResults.put(347, "yes");
			expectedResults.put(348, "yes");
			expectedResults.put(349, "yes");
			expectedResults.put(350, "yes");
			expectedResults.put(351, "no");
			expectedResults.put(352, "no");
			expectedResults.put(353, "no");
			expectedResults.put(354, "no");
			expectedResults.put(355, "no");
			expectedResults.put(356, "no");
			expectedResults.put(357, "yes");
			expectedResults.put(358, "yes");
			expectedResults.put(359, "yes");
			expectedResults.put(360, "no");
			expectedResults.put(361, "no");
			expectedResults.put(362, "no");
			expectedResults.put(363, "no");
			expectedResults.put(364, "no");
			expectedResults.put(365, "yes");
			expectedResults.put(366, "yes");
			expectedResults.put(367, "yes");
			expectedResults.put(368, "yes");
			expectedResults.put(369, "yes");
			expectedResults.put(370, "yes");
			expectedResults.put(371, "yes");
			expectedResults.put(372, "no");
			expectedResults.put(373, "no");
			expectedResults.put(374, "no");
			expectedResults.put(375, "yes");
			expectedResults.put(376, "yes");
			expectedResults.put(377, "yes");
			expectedResults.put(378, "no");
			expectedResults.put(379, "yes");
			expectedResults.put(380, "yes");
			expectedResults.put(381, "yes");
			expectedResults.put(382, "yes");
			expectedResults.put(383, "yes");
			expectedResults.put(384, "yes");
			expectedResults.put(385, "yes");
			expectedResults.put(386, "no");
			expectedResults.put(387, "no");
			expectedResults.put(388, "no");
			expectedResults.put(389, "no");
			expectedResults.put(390, "no");
			expectedResults.put(391, "no");
			expectedResults.put(392, "no");
			expectedResults.put(393, "no");
			expectedResults.put(394, "no");
			expectedResults.put(395, "yes");
			expectedResults.put(396, "yes");
			expectedResults.put(397, "no");
			expectedResults.put(398, "no");
			expectedResults.put(399, "no");
			expectedResults.put(400, "yes");
			expectedResults.put(401, "yes");
			expectedResults.put(402, "yes");
			expectedResults.put(403, "yes");
			expectedResults.put(404, "yes");
			expectedResults.put(405, "yes");
			expectedResults.put(406, "no");
			expectedResults.put(407, "no");
			expectedResults.put(408, "no");
			expectedResults.put(409, "no");
			expectedResults.put(410, "no");
			expectedResults.put(411, "yes");
			expectedResults.put(412, "no");
			expectedResults.put(413, "no");
			expectedResults.put(414, "yes");
			expectedResults.put(415, "yes");
			expectedResults.put(416, "yes");
			expectedResults.put(417, "yes");
			expectedResults.put(418, "no");
			expectedResults.put(419, "no");
			expectedResults.put(420, "yes");
			expectedResults.put(421, "no");
			expectedResults.put(422, "yes");
			expectedResults.put(423, "yes");
			expectedResults.put(424, "yes");
			expectedResults.put(425, "yes");
			expectedResults.put(426, "no");
			expectedResults.put(427, "yes");
			expectedResults.put(428, "yes");
			expectedResults.put(429, "yes");
			expectedResults.put(430, "no");
			expectedResults.put(431, "yes");
			expectedResults.put(432, "yes");
			expectedResults.put(433, "yes");
			expectedResults.put(434, "yes");
			expectedResults.put(435, "no");
			expectedResults.put(436, "yes");
			expectedResults.put(437, "no");
			expectedResults.put(438, "no");
			expectedResults.put(439, "no");
			expectedResults.put(440, "yes");
			expectedResults.put(441, "yes");
			expectedResults.put(442, "yes");
			expectedResults.put(443, "yes");
			expectedResults.put(444, "yes");
			expectedResults.put(445, "yes");
			expectedResults.put(446, "no");
			expectedResults.put(447, "no");
			expectedResults.put(448, "yes");
			expectedResults.put(449, "no");
			expectedResults.put(450, "no");
			expectedResults.put(451, "yes");
			expectedResults.put(452, "no");
			expectedResults.put(453, "no");
			expectedResults.put(454, "no");
			expectedResults.put(455, "yes");
			expectedResults.put(456, "no");
			expectedResults.put(457, "yes");
			expectedResults.put(458, "yes");
			expectedResults.put(459, "no");
			expectedResults.put(460, "yes");
			expectedResults.put(461, "no");
			expectedResults.put(462, "yes");
			expectedResults.put(463, "yes");
			expectedResults.put(464, "yes");
			expectedResults.put(465, "no");
			expectedResults.put(466, "no");
			expectedResults.put(467, "no");
			expectedResults.put(468, "no");
			expectedResults.put(469, "yes");
			expectedResults.put(470, "no");
			expectedResults.put(471, "yes");
			expectedResults.put(472, "no");
			expectedResults.put(473, "no");
			expectedResults.put(474, "no");
			expectedResults.put(475, "yes");
			expectedResults.put(476, "yes");
			expectedResults.put(477, "yes");
			expectedResults.put(478, "yes");
			expectedResults.put(479, "no");
			expectedResults.put(480, "yes");
			expectedResults.put(481, "no");
			expectedResults.put(482, "no");
			expectedResults.put(483, "no");
			expectedResults.put(484, "yes");
			expectedResults.put(485, "no");
			expectedResults.put(486, "no");
			expectedResults.put(487, "yes");
			expectedResults.put(488, "no");
			expectedResults.put(489, "no");
			expectedResults.put(490, "yes");
			expectedResults.put(491, "no");
			expectedResults.put(492, "yes");
			expectedResults.put(493, "yes");
			expectedResults.put(494, "yes");
			expectedResults.put(495, "no");
			expectedResults.put(496, "no");
			expectedResults.put(497, "yes");
			expectedResults.put(498, "no");
			expectedResults.put(499, "no");
			expectedResults.put(500, "no");
			expectedResults.put(501, "yes");
			expectedResults.put(502, "yes");
			expectedResults.put(503, "no");
			expectedResults.put(504, "yes");
			expectedResults.put(505, "no");
			expectedResults.put(506, "yes");
			expectedResults.put(507, "no");
			expectedResults.put(508, "no");
			expectedResults.put(509, "yes");
			expectedResults.put(510, "no");
			expectedResults.put(511, "yes");
			expectedResults.put(512, "yes");
			expectedResults.put(513, "no");
			expectedResults.put(514, "no");
			expectedResults.put(515, "yes");
			expectedResults.put(516, "yes");
			expectedResults.put(517, "yes");
			expectedResults.put(518, "yes");
			expectedResults.put(519, "no");
			expectedResults.put(520, "no");
			expectedResults.put(521, "no");
			expectedResults.put(522, "yes");
			expectedResults.put(523, "yes");
			expectedResults.put(524, "no");
			expectedResults.put(525, "no");
			expectedResults.put(526, "yes");
			expectedResults.put(527, "yes");
			expectedResults.put(528, "no");
			expectedResults.put(529, "no");
			expectedResults.put(530, "1001");
			expectedResults.put(531, "1008");
			expectedResults.put(532, "1004");
		}
}
		